### ISSUE TITLE
海思920处理器出现下面这个问题,google好久没找到原因,编译出来arm64-v8a,armeabi-v7a,x86这几个平台

### ISSUE THREAD

**Issue by MrZhangYang** [begeekmyfriend/yasea#155]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stpcpy" referenced by "libenc.so"...

**Comment by begeekmyfriend** [comment]
NDK building error

**Comment by MrZhangYang** [comment]
是我编译处理的so文件有问题吗?我是在ndk-21,ubuntu下编译的 libx264,

**Comment by MrZhangYang** [comment]
其他手机魅族,三星,还努比亚,我是了都是好的,就华为一款手机有这个问题

**Comment by begeekmyfriend** [comment]
你可以自己改[Application.mk](https://github.com/begeekmyfriend/yasea/blob/master/app/src/main/libenc/jni/Application.mk)

**Comment by MrZhangYang** [comment]
arm64-v8a,armeabi-v7a,x86,这几个平台我编译出来了,目前不确定是我编译的so有问题还是啥

**Comment by begeekmyfriend** [comment]
你改一下android ndk版本号，也有可能海思系统bug，去问问官方

**Comment by MrZhangYang** [comment]
好的我试试,谢谢

**Comment by MrZhangYang** [comment]
编译时候我选择的ndkapi 为21这个对编译出来的,so有影响不,我试了android5.1,armv7a,可以,android4.1.2,armv7a,就报错,arm64v8a android5.0也是可以的

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/yasea/commit/2c4e21603edbae44b108ee3e384cd81e2e2e346f

**Comment by spurd0** [comment]
Hi, have same problem on Samsung s3 using Android 4.4.4. 
Compile config:
    compileSdkVersion 24
    buildToolsVersion "24.0.3"
    minSdkVersion 16
    targetSdkVersion 22

**Comment by laalex** [comment]
Has this been solved? I am still facing this problem with an Android smartwatch. It works fine on a Galaxy S6 edge.

**Comment by begeekmyfriend** [comment]
Please check your Android NDK platform version

**Comment by laalex** [comment]
I tried with Android NDK Platform 21 and I can compile the libs. However anything below that doesn't work. My target device is Android 4.4 (Api level 19). 

Any input on this?

**Comment by laalex** [comment]
NVM. Changed Android NDK platform version and updated libx264 configuration settings and recompiled everything. Now works well with API lvl 19.
