### ISSUE TITLE
writeThread not closed

### ISSUE THREAD

**Issue by gouravd** [begeekmyfriend/yasea#4]
I guess the following is missing in the stop() function in srsEncoder.java. May be that is why the writeThread continues to wait even after stop publishing

if(publisher != null) {
            Log.i(TAG, "stop publisher");
            publisher.shutdown();
        }

**Comment by begeekmyfriend** [comment]
the publisher is closed in `stop()` in `SrsRtmpFlv.java` for it shall end before the worker thread.

So which version do you still meet the problem that `writeThread` continues to wait even after stop publishing?

**Comment by gouravd** [comment]
I was using the version just before this commit. I downloaded the repo yesterday

**Comment by gouravd** [comment]
I just checked the logs, the publisher.closeStream() is throwing so the publisher.shutdown is not closed

E/ReadThread: ReadThread: Caught SocketException while reading/decoding packet, shutting down...
                                                                     java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                         at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
                                                                         at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
                                                                         at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
                                                                         at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                         at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                         at java.io.InputStream.read(InputStream.java:162)
                                                                         at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
                                                                         at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
                                                                         at in.funah.android.rtmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:238)
                                                                         at in.funah.android.rtmp.packets.RtmpHeader.readHeader(RtmpHeader.java:232)
                                                                         at in.funah.android.rtmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36)
                                                                         at in.funah.android.rtmp.io.ReadThread.run(ReadThread.java:37)
                                                                      Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                         at libcore.io.Posix.recvfromBytes(Native Method)
                                                                         at libcore.io.Posix.recvfrom(Posix.java:161)
                                                                         at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                                         at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
                                                                         at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485) 
                                                                         at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37) 
                                                                         at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237) 
                                                                         at java.io.InputStream.read(InputStream.java:162) 
                                                                         at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149) 
                                                                         at java.io.BufferedInputStream.read(BufferedInputStream.java:234) 
                                                                         at in.funah.android.rtmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:238) 
                                                                         at in.funah.android.rtmp.packets.RtmpHeader.readHeader(RtmpHeader.java:232) 
                                                                         at in.funah.android.rtmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:36) 
                                                                         at in.funah.android.rtmp.io.ReadThread.run(ReadThread.java:37)

**Comment by begeekmyfriend** [comment]
That means the peer (server) forced to close the socket. Would you please show me the log of peer (server)?

**Comment by gouravd** [comment]
Actually i was giving a wrong server. 

Should we handle that as following in the disconnect method?

try {
                publisher.closeStream();
            }
            catch (Exception ex)
            {

            }

**Comment by begeekmyfriend** [comment]
That could be the reason why write thread leaks. I do appreciate the point you gave me. And I will do more details to verify that.

**Comment by begeekmyfriend** [comment]
There is no need to take care of the `IllegalStateException` thrown by `closeStream()` at least in the current. Because `closeStream()` could be a NULL operation when some `IOException` occur during thread running and then the `defaultUncaughtExceptionHandler` will do the `closeStream` asynchronously. Therefore the `stop` operation later makes no sense and should be ignored.

**Comment by begeekmyfriend** [comment]
The reason of the write thread leak is found. Yasea sends AV data on getting the response of `NetStream.Publish.Start` which might well be lost in networking when the `publish()` operation is still waiting in a permanent lock. And therefore the write thread can be forgotten even the socket connection thread has been killed.

**Comment by begeekmyfriend** [comment]
Here is the solution https://github.com/begeekmyfriend/yasea/commit/a096d4de94895d2af9ae0fdfac4fe92778368e48, just see the problem has been fixed or not.

**Comment by gouravd** [comment]
Actually that is the correct approach. 

But the problem is still not resolved. The writeThread continues to "wait" indefinitely. My other concern is that apart from publisher.shutdown() being not called, connected might still be true and sequenceHeaderOk might continue to be true because those lines are not executed.

if (publisher != null) {
            publisher.closeStream(); --> This throws and next 3 lines are not executed
            publisher.shutdown();
            connected = false;
            sequenceHeaderOk = false;
        }

**Comment by begeekmyfriend** [comment]
Then how about both exceptions of `closeStream()` and `shutdown()` being ignored? That is the simplest cleanup approach.

**Comment by gouravd** [comment]
Yeah that's what I am using right now.

**Comment by begeekmyfriend** [comment]
Fixed.https://github.com/begeekmyfriend/yasea/commit/0047eefea337df3e4488de7ac77e1a67d04b9c7a

**Comment by begeekmyfriend** [comment]
The read thread seems to throw `EOFException` and exits...

**Comment by begeekmyfriend** [comment]
It seems the patch https://github.com/begeekmyfriend/yasea/commit/0047eefea337df3e4488de7ac77e1a67d04b9c7a results in `EOFException` in read thread on connection. I have no idea what is up.

**Comment by begeekmyfriend** [comment]
It is the time stamp bug. In `RtmpConnection.java`:

···java
invoke.getHeader().setAbsoluteTimestamp((int) (System.nanoTime() / 1000));
···

Set it as 0 will be OK. I will track on this issue. Very sorry, sir...

**Comment by gouravd** [comment]
I am not seeing the readThread EOF problem yet.

**Comment by begeekmyfriend** [comment]
Patch https://github.com/begeekmyfriend/yasea/commit/0e2e7e5e803e33d1b0269802542cc15220170019 and https://github.com/begeekmyfriend/yasea/commit/cc08c9f399c38b83e22c306ba6e4bee50b51ab9a fixed it.
